Задание 1

Часть 1

In [6]:
import numpy as np

In [10]:
a=np.array([i for i in range(12,24)])

In [11]:
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [12]:
np.arange(12,24)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [16]:
a.reshape(2, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [17]:
a.reshape(3,4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [18]:
a.reshape(4, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [20]:
a.reshape(6,2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [21]:
a.reshape(12,1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [22]:
a.reshape(-1,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [23]:
a.reshape(-1,4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [24]:
a.reshape(6, -1)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [25]:
a.reshape(3,-1)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [26]:
a.reshape(4, -1)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

Часть 2

In [29]:
a=np.random.randn(3, 4)

In [30]:
a

array([[-0.85818657, -0.18261702, -0.15800515,  1.03189645],
       [-1.55033559,  0.65469487, -0.85055927,  0.38815487],
       [ 0.89623951,  2.45453453, -0.36683961,  0.50823368]])

In [31]:
a.size

12

In [32]:
b=a.flatten()

In [33]:
b

array([-0.85818657, -0.18261702, -0.15800515,  1.03189645, -1.55033559,
        0.65469487, -0.85055927,  0.38815487,  0.89623951,  2.45453453,
       -0.36683961,  0.50823368])

In [34]:
b.size

12

Часть 3

In [35]:
a=np.arange(20,0,-2)

In [36]:
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [40]:
b=np.arange(20,1,-2)

In [41]:
b.reshape(1,10)

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

Часть 4

In [60]:
a=np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [58]:
b=np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [61]:
v=np.vstack((a,b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [62]:
v.size

10

Часть 5

In [64]:
a=np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [66]:
A=a.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [68]:
At=A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [69]:
B=np.dot(A,At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [71]:
B.shape

(4, 4)

часть 6

In [76]:
np.random.seed(42)
a=np.random.randint(0, 16, 16)

In [78]:
C=np.reshape(a, (4,4))
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [79]:
C=C*10
C

array([[ 60,  30, 120, 140],
       [100,  70, 120,  40],
       [ 60,  90,  20,  60],
       [100, 100,  70,  40]])

In [80]:
D=C+B
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [81]:
np.linalg.det(D)

-28511999.999999944

In [82]:
np.linalg.matrix_rank(B)

2

In [83]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

Часть 7

In [118]:
D_inv[np.where(D_inv>0)]= 1
D_inv

array([[ 1.        ,  1.        ,  1.        , -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  1.        ],
       [-0.00356692, -0.01782828, -0.04152146,  1.        ],
       [ 1.        , -0.00181818,  1.        , -0.01090909]])

In [119]:
D_inv[np.where(D_inv<0)]= 0
D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [121]:
E=np.where(D_inv==1,B,C)
E

array([[  5,  14,  23, 140],
       [100,  70, 120, 122],
       [ 60,  90,  20, 212],
       [ 32, 100, 212,  40]])

Задание 2

In [110]:
Numpy = np.array([[1, 6],
                  [2,8],
                  [3,11],
                  [3,10],
                  [1,7]])

In [111]:
Numpy

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [113]:
mean_a=Numpy.mean(axis=0)
mean_a

array([2. , 8.4])

Задание 3

In [115]:
a_centered=Numpy-mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

задание 4

In [116]:
a_centered.dot(axis=0)

TypeError: dot() missing required argument 'b' (pos 1)